# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import container_service_pb2 as container__service__pb2


class ContainerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.retrieve_container_core_information = channel.unary_unary(
                '/ContainerService/retrieve_container_core_information',
                request_serializer=container__service__pb2.Container_Service_Input.SerializeToString,
                response_deserializer=container__service__pb2.Core_Information_Output.FromString,
                )
        self.retrieve_container_cpu_usage_information = channel.unary_unary(
                '/ContainerService/retrieve_container_cpu_usage_information',
                request_serializer=container__service__pb2.Container_Service_Input.SerializeToString,
                response_deserializer=container__service__pb2.CPU_Usage_Output.FromString,
                )
        self.retrieve_cpu_freq_information = channel.unary_unary(
                '/ContainerService/retrieve_cpu_freq_information',
                request_serializer=container__service__pb2.Container_Service_Input.SerializeToString,
                response_deserializer=container__service__pb2.CPU_Freq_Output.FromString,
                )


class ContainerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def retrieve_container_core_information(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieve_container_cpu_usage_information(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieve_cpu_freq_information(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'retrieve_container_core_information': grpc.unary_unary_rpc_method_handler(
                    servicer.retrieve_container_core_information,
                    request_deserializer=container__service__pb2.Container_Service_Input.FromString,
                    response_serializer=container__service__pb2.Core_Information_Output.SerializeToString,
            ),
            'retrieve_container_cpu_usage_information': grpc.unary_unary_rpc_method_handler(
                    servicer.retrieve_container_cpu_usage_information,
                    request_deserializer=container__service__pb2.Container_Service_Input.FromString,
                    response_serializer=container__service__pb2.CPU_Usage_Output.SerializeToString,
            ),
            'retrieve_cpu_freq_information': grpc.unary_unary_rpc_method_handler(
                    servicer.retrieve_cpu_freq_information,
                    request_deserializer=container__service__pb2.Container_Service_Input.FromString,
                    response_serializer=container__service__pb2.CPU_Freq_Output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ContainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContainerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def retrieve_container_core_information(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerService/retrieve_container_core_information',
            container__service__pb2.Container_Service_Input.SerializeToString,
            container__service__pb2.Core_Information_Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def retrieve_container_cpu_usage_information(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerService/retrieve_container_cpu_usage_information',
            container__service__pb2.Container_Service_Input.SerializeToString,
            container__service__pb2.CPU_Usage_Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def retrieve_cpu_freq_information(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerService/retrieve_cpu_freq_information',
            container__service__pb2.Container_Service_Input.SerializeToString,
            container__service__pb2.CPU_Freq_Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
