# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynamic_core_allocator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64ynamic_core_allocator.proto\";\n\x0b\x43ore_Inputs\x12\x13\n\x0b\x64omain_name\x18\x01 \x01(\t\x12\x17\n\x0fnumber_of_cores\x18\x02 \x01(\x05\"\x1d\n\x0b\x43ore_Output\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x45\n\x14\x44ynamicCoreAllocator\x12-\n\rallocate_core\x12\x0c.Core_Inputs\x1a\x0c.Core_Output\"\x00\x62\x06proto3')



_CORE_INPUTS = DESCRIPTOR.message_types_by_name['Core_Inputs']
_CORE_OUTPUT = DESCRIPTOR.message_types_by_name['Core_Output']
Core_Inputs = _reflection.GeneratedProtocolMessageType('Core_Inputs', (_message.Message,), {
  'DESCRIPTOR' : _CORE_INPUTS,
  '__module__' : 'dynamic_core_allocator_pb2'
  # @@protoc_insertion_point(class_scope:Core_Inputs)
  })
_sym_db.RegisterMessage(Core_Inputs)

Core_Output = _reflection.GeneratedProtocolMessageType('Core_Output', (_message.Message,), {
  'DESCRIPTOR' : _CORE_OUTPUT,
  '__module__' : 'dynamic_core_allocator_pb2'
  # @@protoc_insertion_point(class_scope:Core_Output)
  })
_sym_db.RegisterMessage(Core_Output)

_DYNAMICCOREALLOCATOR = DESCRIPTOR.services_by_name['DynamicCoreAllocator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CORE_INPUTS._serialized_start=32
  _CORE_INPUTS._serialized_end=91
  _CORE_OUTPUT._serialized_start=93
  _CORE_OUTPUT._serialized_end=122
  _DYNAMICCOREALLOCATOR._serialized_start=124
  _DYNAMICCOREALLOCATOR._serialized_end=193
# @@protoc_insertion_point(module_scope)
