# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: container_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ontainer_service.proto\".\n\x17\x43ontainer_Service_Input\x12\x13\n\x0b\x64omain_name\x18\x01 \x01(\t\"2\n\x17\x43ore_Information_Output\x12\x17\n\x0fnumber_of_cores\x18\x01 \x01(\x05\"%\n\x10\x43PU_Usage_Output\x12\x11\n\tcpu_usage\x18\x01 \x01(\x01\"#\n\x0f\x43PU_Freq_Output\x12\x10\n\x08\x63pu_freq\x18\x01 \x01(\x01\x32\x99\x02\n\x10\x43ontainerService\x12[\n#retrieve_container_core_information\x12\x18.Container_Service_Input\x1a\x18.Core_Information_Output\"\x00\x12Y\n(retrieve_container_cpu_usage_information\x12\x18.Container_Service_Input\x1a\x11.CPU_Usage_Output\"\x00\x12M\n\x1dretrieve_cpu_freq_information\x12\x18.Container_Service_Input\x1a\x10.CPU_Freq_Output\"\x00\x62\x06proto3')



_CONTAINER_SERVICE_INPUT = DESCRIPTOR.message_types_by_name['Container_Service_Input']
_CORE_INFORMATION_OUTPUT = DESCRIPTOR.message_types_by_name['Core_Information_Output']
_CPU_USAGE_OUTPUT = DESCRIPTOR.message_types_by_name['CPU_Usage_Output']
_CPU_FREQ_OUTPUT = DESCRIPTOR.message_types_by_name['CPU_Freq_Output']
Container_Service_Input = _reflection.GeneratedProtocolMessageType('Container_Service_Input', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINER_SERVICE_INPUT,
  '__module__' : 'container_service_pb2'
  # @@protoc_insertion_point(class_scope:Container_Service_Input)
  })
_sym_db.RegisterMessage(Container_Service_Input)

Core_Information_Output = _reflection.GeneratedProtocolMessageType('Core_Information_Output', (_message.Message,), {
  'DESCRIPTOR' : _CORE_INFORMATION_OUTPUT,
  '__module__' : 'container_service_pb2'
  # @@protoc_insertion_point(class_scope:Core_Information_Output)
  })
_sym_db.RegisterMessage(Core_Information_Output)

CPU_Usage_Output = _reflection.GeneratedProtocolMessageType('CPU_Usage_Output', (_message.Message,), {
  'DESCRIPTOR' : _CPU_USAGE_OUTPUT,
  '__module__' : 'container_service_pb2'
  # @@protoc_insertion_point(class_scope:CPU_Usage_Output)
  })
_sym_db.RegisterMessage(CPU_Usage_Output)

CPU_Freq_Output = _reflection.GeneratedProtocolMessageType('CPU_Freq_Output', (_message.Message,), {
  'DESCRIPTOR' : _CPU_FREQ_OUTPUT,
  '__module__' : 'container_service_pb2'
  # @@protoc_insertion_point(class_scope:CPU_Freq_Output)
  })
_sym_db.RegisterMessage(CPU_Freq_Output)

_CONTAINERSERVICE = DESCRIPTOR.services_by_name['ContainerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTAINER_SERVICE_INPUT._serialized_start=27
  _CONTAINER_SERVICE_INPUT._serialized_end=73
  _CORE_INFORMATION_OUTPUT._serialized_start=75
  _CORE_INFORMATION_OUTPUT._serialized_end=125
  _CPU_USAGE_OUTPUT._serialized_start=127
  _CPU_USAGE_OUTPUT._serialized_end=164
  _CPU_FREQ_OUTPUT._serialized_start=166
  _CPU_FREQ_OUTPUT._serialized_end=201
  _CONTAINERSERVICE._serialized_start=204
  _CONTAINERSERVICE._serialized_end=485
# @@protoc_insertion_point(module_scope)
