# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dynamic_core_allocator_pb2 as dynamic__core__allocator__pb2


class DynamicCoreAllocatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.allocate_core = channel.unary_unary(
                '/DynamicCoreAllocator/allocate_core',
                request_serializer=dynamic__core__allocator__pb2.Core_Inputs.SerializeToString,
                response_deserializer=dynamic__core__allocator__pb2.Core_Output.FromString,
                )


class DynamicCoreAllocatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def allocate_core(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DynamicCoreAllocatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'allocate_core': grpc.unary_unary_rpc_method_handler(
                    servicer.allocate_core,
                    request_deserializer=dynamic__core__allocator__pb2.Core_Inputs.FromString,
                    response_serializer=dynamic__core__allocator__pb2.Core_Output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DynamicCoreAllocator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DynamicCoreAllocator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def allocate_core(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DynamicCoreAllocator/allocate_core',
            dynamic__core__allocator__pb2.Core_Inputs.SerializeToString,
            dynamic__core__allocator__pb2.Core_Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
