# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pegasus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpegasus.proto\"\x83\x02\n\x0ePegasus_Inputs\x12\"\n\x1anumber_of_lines_to_be_read\x18\x01 \x01(\x05\x12\x15\n\rsampling_time\x18\x02 \x01(\x05\x12\x17\n\x0ftune_percentage\x18\x03 \x01(\x02\x12\x1c\n\x14\x61pplication_sub_path\x18\x04 \x01(\t\x12\x1c\n\x14\x63ontroller_data_file\x18\x05 \x01(\t\x12\x11\n\tref_input\x18\x06 \x01(\x05\x12\x10\n\x08log_file\x18\x07 \x01(\t\x12\x1c\n\x14retraining_threshold\x18\x08 \x01(\x05\x12\x0e\n\x06pi_min\x18\t \x01(\x05\x12\x0e\n\x06pi_max\x18\n \x01(\x05\" \n\x0ePegasus_Output\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32M\n\x0ePegasusManager\x12;\n\x15\x62\x65gin_pegasus_manager\x12\x0f.Pegasus_Inputs\x1a\x0f.Pegasus_Output\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pegasus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PEGASUS_INPUTS._serialized_start=18
  _PEGASUS_INPUTS._serialized_end=277
  _PEGASUS_OUTPUT._serialized_start=279
  _PEGASUS_OUTPUT._serialized_end=311
  _PEGASUSMANAGER._serialized_start=313
  _PEGASUSMANAGER._serialized_end=390
# @@protoc_insertion_point(module_scope)
