# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rapl_power_monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18rapl_power_monitor.proto\"\n\n\x08No_Input\"#\n\x0cPower_Output\x12\x13\n\x0bpower_value\x18\x01 \x01(\x01\"6\n\x0bWrite_Input\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x14\n\x0cpower_values\x18\x02 \x01(\t\"\x1e\n\x0cWrite_Output\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32k\n\x0cPowerMonitor\x12+\n\raverage_power\x12\t.No_Input\x1a\r.Power_Output\"\x00\x12.\n\rwrite_to_file\x12\x0c.Write_Input\x1a\r.Write_Output\"\x00\x62\x06proto3')



_NO_INPUT = DESCRIPTOR.message_types_by_name['No_Input']
_POWER_OUTPUT = DESCRIPTOR.message_types_by_name['Power_Output']
_WRITE_INPUT = DESCRIPTOR.message_types_by_name['Write_Input']
_WRITE_OUTPUT = DESCRIPTOR.message_types_by_name['Write_Output']
No_Input = _reflection.GeneratedProtocolMessageType('No_Input', (_message.Message,), {
  'DESCRIPTOR' : _NO_INPUT,
  '__module__' : 'rapl_power_monitor_pb2'
  # @@protoc_insertion_point(class_scope:No_Input)
  })
_sym_db.RegisterMessage(No_Input)

Power_Output = _reflection.GeneratedProtocolMessageType('Power_Output', (_message.Message,), {
  'DESCRIPTOR' : _POWER_OUTPUT,
  '__module__' : 'rapl_power_monitor_pb2'
  # @@protoc_insertion_point(class_scope:Power_Output)
  })
_sym_db.RegisterMessage(Power_Output)

Write_Input = _reflection.GeneratedProtocolMessageType('Write_Input', (_message.Message,), {
  'DESCRIPTOR' : _WRITE_INPUT,
  '__module__' : 'rapl_power_monitor_pb2'
  # @@protoc_insertion_point(class_scope:Write_Input)
  })
_sym_db.RegisterMessage(Write_Input)

Write_Output = _reflection.GeneratedProtocolMessageType('Write_Output', (_message.Message,), {
  'DESCRIPTOR' : _WRITE_OUTPUT,
  '__module__' : 'rapl_power_monitor_pb2'
  # @@protoc_insertion_point(class_scope:Write_Output)
  })
_sym_db.RegisterMessage(Write_Output)

_POWERMONITOR = DESCRIPTOR.services_by_name['PowerMonitor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NO_INPUT._serialized_start=28
  _NO_INPUT._serialized_end=38
  _POWER_OUTPUT._serialized_start=40
  _POWER_OUTPUT._serialized_end=75
  _WRITE_INPUT._serialized_start=77
  _WRITE_INPUT._serialized_end=131
  _WRITE_OUTPUT._serialized_start=133
  _WRITE_OUTPUT._serialized_end=163
  _POWERMONITOR._serialized_start=165
  _POWERMONITOR._serialized_end=272
# @@protoc_insertion_point(module_scope)
